[package]
name = "im-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
im-common = { path = "../im-common" }
im-proto = { path = "../im-proto" }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
prost = { workspace = true }
flate2 = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
