[package]
name = "im-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints.rust]
missing_docs = "warn"

[dependencies]
im-proto = { path = "../im-proto" }
im-common = { path = "../im-common" }
sqlx = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
chrono = { workspace = true, features = ["serde"] }
